### ISSUE TITLE
Enable using docker build `--platform` switch (easily)

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4388]
There is no way to write a Dockerfile for .NET that is (A) succinct, (B) easy to build from the command line, (C) can equally produce Arm64 or x64 images, (D) that will run equally well on both Arm64 and x64 machines, and (E) avoids running the SDK in an emulator (since .NET doesn't support running in QEMU).

The following Dockerfile (which doesn't currently work) would satisfy all four of these requirements.

```Dockerfile
ARG BUILDARCH
FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim-$BUILDARCH AS build
ARG TARGETARCH
WORKDIR /source

# copy csproj and restore as distinct layers
COPY aspnetapp/*.csproj .
RUN dotnet restore -r linux-$TARGETARCH

# copy everything else and build app
COPY aspnetapp/. .
RUN dotnet publish -c Release -r linux-$TARGETARCH --self-contained false --no-restore -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./aspnetapp"]
```

Note: The two ENVs are set via Docker, not my invention. Context: https://github.com/dotnet/dotnet-docker/pull/4387#issuecomment-1416565213. The reason this `Dockerfile` doesn't work is because `-r` expects `x64` not `amd64` (which `$TARGETARCH` returns) and our container tags expect `arm64v8` not `arm64` (which `$BUILDARCH` returns). Funny enough, `$TARGETARCH` returns `arm64` for Arm64, which `-r` likes fine and `$BUILDARCH` returns `amd64` for x64, which our container tags like fine.

Note: Close readers may wonder why `$TARGETARCH` is not needed for the last `FROM` statement. That's because `--platform` is picking the correct image from the multi-arch tag. We could use $`TARGETARCH` if we wanted, but it is unnecessary since the underlying mechanics will do the right thing. How would one know that the tag is a multi-arch tag just by looking at it? It's because it doesn't include an architecture.

It would enable the following scenarios:

- `docker build` -- will produce a native-arch result on both Arm64 and x64 and use the native arch SDK.
- `docker build --platform linux/arm64` -- Will produce an Arm64 container image on both Arm64 and x64 machines but run the  SDK as native-arch, avoiding emulation (on x64 machines).
- `docker build --platform linux/amd64` -- Same as above, but will produce an x64 container images, and similarly avoid emulation (on Arm64 machines).
- `docker buildx build --platform linux/amd64,linux/arm64` -- Same as above, but will produce both Arm64 and x64 container images, and similarly avoid emulation.

Note that the resulting image will not run in emulation. That's the not the purpose of this proposal. Instead, the purpose is to reliably avoid emulation and to make it easy, for example, to build x64 container images on an Apple M1 box and push those to an x64 cloud. You'd be able to do that via the `--platform` switch and not need to do anything else (other than follow the pattern used in the Dockerfile).

It requires two things:

- For Arm64, we need to push container tags as `arm64` (matching `$BUILDARCH`) in addition to `arm64v8`.
- For x64, teaching the CLI to replace `linux-amd64` (matching `$TARGETARCH`) with `linux-x64`

The proposal is to make these changes for .NET 6+.

The alternative is the following.

```Dockerfile
ARG SDKARCH=amd64
FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim-$SDKARCH AS build

ARG TARGETARCH
RUN arch=$TARGETARCH \
    && if [ "$TARGETARCH" = "amd64" ]; then arch="x64"; fi \
    && echo $arch > /tmp/arch

WORKDIR /source

# copy csproj and restore as distinct layers
COPY aspnetapp/*.csproj .
RUN dotnet restore -r linux-$(cat /tmp/arch)

# copy everything else and build app
COPY aspnetapp/. .
RUN dotnet publish -r linux-$(cat /tmp/arch) -c Release --self-contained false --no-restore -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./aspnetapp"]
```

Inspiration: https://github.com/dotnet/dotnet-docker/pull/4387#issuecomment-1416454071

`SDKARCH` needs to have a default, so you need to know to set the `ARG` on whatever platform isn't the default. Here, I'm choosing x64 (or really "amd64") as the default. Also, you cannot run any code before the first `FROM` since a Dockerfile isn't `bash`.

This pattern enables the following scenarios:

- `docker build` -- only works correctly on x64 and breaks on Arm64 (`dotnet restore` just hangs),
- `docker build --build-arg SDKARCH=arm64v8` -- builds an Arm64 image on an Arm64 machine, not because the `ARG` is set, however. The `ARG` just enables the SDK to run with the native arch.
- `docker build --platform linux/arm64` -- Doesn't do anything useful, same for specifying `linux/amd64`.
- `docker build buildx --platform linux/amd64,linux/arm64` -- Doesn't work.
- `docker build buildx --platform linux/amd64,linux/arm64 --build-arg SDKARCH=arm64v8` -- Produces both Arm64 and x64 container images.

**Comment by richlander** [comment]
@nagilson  @baronfel @marcpopMSFT

**Comment by mthalman** [comment]
[Triage]
Short-term we need to update our customer guidance for this scenario since the current guidance is incompatible with the functionality of .NET 7. The alternative Dockerfile that was provided above with the `SDKARCH` is probably the best approach identified at this point for a workable solution that's possible today.

Long-term we need to come up with a design that can work. Ideally it would be great if we could eliminate the need for a set of variant-less tags (e.g. `arm64`). There does exist a `$TARGETVARIANT` variable that may help with this. But it seems to only be set for Arm32 scenarios. Then we'd need to get buyoff from the CLI for implementing some kind of RID aliasing between x64 and amd64.

**Comment by MichaelSimons** [comment]
@richlander, In your proposed Dockerfile

```
ARG BUILDARCH
FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim-$BUILDARCH AS build
ARG TARGETARCH
WORKDIR /source

# copy csproj and restore as distinct layers
COPY aspnetapp/*.csproj .
RUN dotnet restore -r linux-$TARGETARCH

# copy everything else and build app
COPY aspnetapp/. .
RUN dotnet publish -c Release -r linux-$TARGETARCH --self-contained false --no-restore -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./aspnetapp"]
```

Have you considered utilizing the `--platform` option within the `FROM` statement?  This feels like it could simplify the Dockerfile, work with the existing Dockerfile constructs, and not require any tagging derivations from the _norm_.

```
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim AS build
ARG TARGETARCH
WORKDIR /source

# copy csproj and restore as distinct layers
COPY aspnetapp/*.csproj .
RUN dotnet restore -r linux-$TARGETARCH

# copy everything else and build app
COPY aspnetapp/. .
RUN dotnet publish -c Release -r linux-$TARGETARCH --self-contained false --no-restore -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./aspnetapp"]
```

**Comment by richlander** [comment]
That looks awesome! Ship it! I didn't know about that pattern.

That means we just need to fix the RID problem.

**Comment by richlander** [comment]
Just wonder about this and Native AOT. Will this pattern not work for that? I think it doesn't have a cross-arch cross-build story. Is that right @jkotas?

**Comment by jkotas** [comment]
NativeAOT has cross-arch cross-build story. It is documented here: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation . For Linux, it requires rootfs matching the target platform.

**Comment by jkotas** [comment]
If it helps, https://github.com/dotnet/samples/tree/main/core/nativeaot/HelloWorld is nativeaot sample that includes Linux x64 and Windows x64 docker files for building it (the sample does not have cross-arch build support).

**Comment by mthalman** [comment]
Issue for NativeAOT scenario investigation is at https://github.com/dotnet/dotnet-docker/issues/4129

**Comment by nagilson** [comment]
> That means we just need to fix the RID problem.

The RID fix is in, a new hire on our team @JL03-Yue worked on it. 😄  Is there anything else required here?

**Comment by richlander** [comment]
It works great! I tested it with [dotnetapp](https://github.com/dotnet/dotnet-docker/tree/main/samples/dotnetapp) and the following Dockerfile.

The Dockerfile references a multi-platform tag container a .NET 8 Preview 3 SDK. That image will be deleted before long, so don't be surprised if you read this later and the sample doesn't work. You'll need to switch to the real .NET 8 SDK image.

```dockerfile
# To learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM --platform=$BUILDPLATFORM dotnetnonroot.azurecr.io/sdk:latest AS build
ARG TARGETARCH
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore -a $TARGETARCH

# copy and publish app and libraries
COPY . .
RUN dotnet publish -a $TARGETARCH --self-contained false --no-restore -o /app

# To enable globalization:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md
# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:7.0-jammy
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./dotnetapp"]
```

Some quick tests.

```bash
% docker build -t dotnetapp .
% docker inspect dotnetapp -f "{{.Os}}\{{.Architecture}}"
linux\arm64
% docker run --rm dotnetapp | grep Arch        
OSArchitecture: Arm64
% docker build -t dotnetapp --platform linux/arm64 .
% docker inspect dotnetapp -f "{{.Os}}\{{.Architecture}}"
linux\arm64
% docker run --rm dotnetapp | grep Arch
OSArchitecture: Arm64
% docker build -t dotnetapp --platform linux/amd64  .
% docker inspect dotnetapp -f "{{.Os}}\{{.Architecture}}"
linux\amd64
% docker build -t dotnetapp --platform linux/arm .
% docker inspect dotnetapp -f "{{.Os}}\{{.Architecture}}"
linux\arm
```

We can have even more fun with `docker buildx`.

```bash
% docker buildx build -f Dockerfile.ubuntu --platform linux/amd64,linux/arm64,linux/arm -t dotnetnonroot.azurecr.io/dotnetapp --push .
```

On my Apple M1 machine:

```bash
% docker run --rm -it dotnetnonroot.azurecr.io/dotnetapp
         42                                                    
         42              ,d                             ,d     
         42              42                             42     
 ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM  
a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42     
8b       42 8b       d8  42    42       42 8PP!!!!!!!   42     
"8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,    
 `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428  

.NET 7.0.3
Ubuntu 22.04.2 LTS

UserName: root
OSArchitecture: Arm64
ProcessorCount: 4
TotalAvailableMemoryBytes: 4124512256 (3.00 GiB)
```

**Comment by richlander** [comment]
This experience will ship in:

- 8.0 P3
- 7.0.300

**Comment by richlander** [comment]
If you want this experience now, you can use: `mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview`

**Comment by goncalo-oliveira** [comment]
> If you want this experience now, you can use: `mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview`

Excellent news @richlander! Thanks for this. I've tried this on my M1 and on a x64 machine and was able to successfully build amd64 and arm64 with buildx on both.

```
docker buildx build --platform linux/amd64,linux/arm64 -t image:tag . --no-cache
```

**Comment by campbellwray** [comment]
@richlander I seem to be having some issues with the `RUN dotnet` lines in the [Dockerfile you provided ](https://github.com/dotnet/dotnet-docker/issues/4388#issuecomment-1459038566)

The command I am using is similar to @goncalo-oliveira's `docker buildx` one but I suspect their Dockerfile might have omitted the `-a $TARGETARCH` switches.

1. `dotnet restore ` doesn't appear to have an `-a` flag
2. `dotnet publish` appears to be expecting `linux-x64` but instead it is getting `linux-amd64` - [Linux RIDs](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids)

Thanks for looking into this

**Comment by richlander** [comment]
Both your observations are 100% true. You've also identified what we fixed in 8.0 P3 and (in future) 7.0.300.

You can try this with the 8.0 P3 nightly build I shared above. Those issues have been resolved. Please try and tell us if it works for you. We'd certainly appreciate knowing that we've polished off all the rough edges.

**Comment by campbellwray** [comment]
Ahh apologies, I was using `mcr.microsoft.com/dotnet/nightly/aspnet:8.0-preview-bullseye-slim`, I didn't realise that there was no `bullseye` version of P3 available, I must have been downloading a much older build.

Unfortunately even with this resolved I was still unable to compile my project, it is `aspnet` and not `runtime`, and it is complaining that version 8.0 P3 is not available for the `Microsoft.NETCore.App.Host.linux-arm64` package on NuGet.

```
error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-arm64 with version (= 8.0.0-preview.3.23165.10)
error NU1102:   - Found 117 version(s) in nuget.org [ Nearest version: 8.0.0-preview.2.23128.3 ]
```

I supposed that means that I will need to wait for either 8.0 P3 or 7.0.300 to be publicly released

**Comment by richlander** [comment]
We moved to Bookworm -> https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-1/#net-container-images

Ya. You get those errors with nightly builds. Try adding this `nuget.config`: https://github.com/dotnet/installer#installers-and-binaries

**Comment by goncalo-oliveira** [comment]
> Unfortunately even with this resolved I was still unable to compile my project, it is aspnet and not runtime, and it is complaining that version 8.0 P3 is not available for the Microsoft.NETCore.App.Host.linux-arm64 package on NuGet.

@campbellwray are you by any chance using 8.0 P3 on the runtime also? You only need 8.0 P3 on the builder side of things. On the runtime, you should probably continue using 7.0.

This is the `Dockerfile` I'm using, without issues on both arm64 and amd64 machines, building with `--platform linux/amd64,linux/arm64` on both.

```Dockerfile
# Builder
# 
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview AS build
ARG TARGETARCH

# ...
RUN dotnet restore -a $TARGETARCH

# ...
RUN dotnet publish -c release -a $TARGETARCH -o dist project.csproj

# Runtime
# 
FROM mcr.microsoft.com/dotnet/aspnet:7.0 as final

# ...
```

**Comment by campbellwray** [comment]
@goncalo-oliveira thank you! I am quite new with Docker for .NET and didn't realise I could build with .NET 8 but continue to run with .NET 7, this is very helpful and has resolved my issues

Thanks again to you both 🥇

**Comment by richlander** [comment]
This is correct. Newer SDKs support building projects that target older .NET versions. The SDK downloads the targeting pack and any other assets required.

Separately, the way that ENVs work in Dockerfiles can be a bit confusing. You need to ensure you have a `ARG TARGETARCH` line within the build stage where you use it. If you put that line right after the `FROM`, it works. Some Dockerfiles have different structures. For example, if we were to upgrade the following Dockerfile, the `ENV` would appear at line 9, not line 4.

https://github.com/dotnet/AspNetCore.Docs.Samples/blob/2f3a9a6af0e4fb5289d880b6003771ed458c5bdd/tutorials/scalable-razor-apps/start/Dockerfile#L8-L9

**Comment by richlander** [comment]
FYI: https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/

**Comment by ptr727** [comment]
I know this issue is closed, please redirect to an appropriate place to discuss?

I found this issues in trying to create multiarch images.  
Using the provided info I create a staged pipeline build, as described above.

But I have an unexplained error, when I try to run the .NET 7 binary on the final layer, I get a `No such file or directory` error, while `ls -la` shows the file is right there?

My hunch is that a library dependency may be missing that prevents the loader from loading, but I am just geuessing.


https://github.com/ptr727/PlexCleaner/blob/multiarch/Docker/MultiArch.Dockerfile

Couple snippets:

```
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview-alpine AS builder
WORKDIR /Builder
```

```
RUN dotnet publish ./PlexCleaner.csproj \
    --arch $TARGETARCH \
    --self-contained false \
    --output ./Publish \
    --configuration $BUILD_CONFIGURATION \
    -property:Version=$BUILD_VERSION \
    -property:FileVersion=$BUILD_FILE_VERSION \
    -property:AssemblyVersion=$BUILD_ASSEMBLY_VERSION \
    -property:InformationalVersion=$BUILD_INFORMATION_VERSION \
    -property:PackageVersion=$BUILD_PACKAGE_VERSION
```

```
#12 [builder 4/5] RUN dotnet publish ./PlexCleaner.csproj     --arch amd64     --self-contained false     --output ./Publish     --configuration Release     -property:Version=1.0.0.0     -property:FileVersion=1.0.0.0     -property:AssemblyVersion=1.0.0.0     -property:InformationalVersion=1.0.0.0     -property:PackageVersion=1.0.0.0
#12 0.932 MSBuild version 17.6.0-preview-23174-01+e7de13307 for .NET
#12 1.817   Determining projects to restore...
#12 5.235   Restored /Builder/PlexCleaner.csproj (in 2.92 sec).
#12 5.323 /usr/share/dotnet/sdk/8.0.100-preview.3.23178.7/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Builder/PlexCleaner.csproj]
#12 5.541 /root/.nuget/packages/microsoft.build.tasks.git/1.1.1/build/Microsoft.Build.Tasks.Git.targets(25,5): warning : Unable to locate repository with working directory that contains directory '/Builder'. [/Builder/PlexCleaner.csproj]
#12 5.570 /root/.nuget/packages/microsoft.build.tasks.git/1.1.1/build/Microsoft.Build.Tasks.Git.targets(48,5): warning : Unable to locate repository with working directory that contains directory '/Builder'. [/Builder/PlexCleaner.csproj]
#12 5.576 /root/.nuget/packages/microsoft.sourcelink.common/1.1.1/build/Microsoft.SourceLink.Common.targets(53,5): warning : Source control information is not available - the generated source link is empty. [/Builder/PlexCleaner.csproj]
#12 ...
```

```
#12 [builder 4/5] RUN dotnet publish ./PlexCleaner.csproj     --arch amd64     --self-contained false     --output ./Publish     --configuration Release     -property:Version=1.0.0.0     -property:FileVersion=1.0.0.0     -property:AssemblyVersion=1.0.0.0     -property:InformationalVersion=1.0.0.0     -property:PackageVersion=1.0.0.0
#12 9.187   PlexCleaner -> /Builder/bin/Release/net7.0/linux-musl-x64/PlexCleaner.dll
#12 9.216   PlexCleaner -> /Builder/Publish/
#12 DONE 9.4s
```

```
ENV DOTNET_ROLL_FORWARD=Major
ENV DOTNET_ROLL_FORWARD_PRE_RELEASE=1
RUN ./Publish/PlexCleaner --version
```

```
#13 [builder 5/5] RUN ./Publish/PlexCleaner --version
#0 0.362 1.0.0.0
#13 DONE 0.4s
```


```
FROM mcr.microsoft.com/dotnet/sdk:latest
```

```
COPY --from=builder /Builder/Publish/. /PlexCleaner
```

```
docker buildx build --load --progress plain --no-cache --platform linux/amd64 --tag testing:latest --file ./Docker/MultiArch.Dockerfile .
```

```
docker run -it --rm --name Testing testing:latest /bin/bash
```

```
root@3fda613a8159:/PlexCleaner# ls -la
total 4852
drwxr-xr-x 15 root root    4096 Apr  8 19:30 .
drwxr-xr-x  1 root root    4096 Apr  8 19:33 ..
drwxr-xr-x  2 root root    4096 Apr  8 19:30 cs
drwxr-xr-x  2 root root    4096 Apr  8 19:30 de
drwxr-xr-x  2 root root    4096 Apr  8 19:30 es
drwxr-xr-x  2 root root    4096 Apr  8 19:30 fr
-rwxr--r--  1 root root 2805248 Apr  5 03:55 InsaneGenius.Utilities.dll
drwxr-xr-x  2 root root    4096 Apr  8 19:30 it
drwxr-xr-x  2 root root    4096 Apr  8 19:30 ja
drwxr-xr-x  2 root root    4096 Apr  8 19:30 ko
-rwxr--r--  1 root root   36360 Jul 25  2017 Microsoft.Extensions.DependencyInjection.Abstractions.dll
-rwxr--r--  1 root root   46600 Jul 25  2017 Microsoft.Extensions.Logging.Abstractions.dll
-rwxr--r--  1 root root   30728 Jul 25  2017 Microsoft.Extensions.Logging.dll
-rwxr--r--  1 root root   26120 Jul 25  2017 Microsoft.Extensions.Options.dll
-rwxr--r--  1 root root   33288 Jul 25  2017 Microsoft.Extensions.Primitives.dll
-rwxr--r--  1 root root  712464 Mar  8 07:09 Newtonsoft.Json.dll
-rwxr--r--  1 root root  253952 Feb 21  2021 Newtonsoft.Json.Schema.dll
drwxr-xr-x  2 root root    4096 Apr  8 19:30 pl
-rwxr-xr-x  1 root root   78288 Apr  8 19:30 PlexCleaner
-rw-r--r--  1 root root   14538 Apr  8 19:30 PlexCleaner.deps.json
-rw-r--r--  1 root root  241664 Apr  8 19:30 PlexCleaner.dll
-rw-r--r--  1 root root   87080 Apr  8 19:30 PlexCleaner.pdb
-rw-r--r--  1 root root     242 Apr  8 19:30 PlexCleaner.runtimeconfig.json
drwxr-xr-x  2 root root    4096 Apr  8 19:30 pt-BR
drwxr-xr-x  2 root root    4096 Apr  8 19:30 ru
-rwxr--r--  1 root root  141824 Sep 13  2022 Serilog.dll
-rwxr--r--  1 root root    6144 May  2  2019 Serilog.Enrichers.Thread.dll
-rwxr--r--  1 root root   17408 Nov  1  2021 Serilog.Extensions.Logging.dll
-rwxr--r--  1 root root    9216 Jun 25  2021 Serilog.Sinks.Async.dll
-rwxr--r--  1 root root   35328 Sep  6  2022 Serilog.Sinks.Console.dll
-rwxr--r--  1 root root   31232 Jun 25  2021 Serilog.Sinks.File.dll
-rwxr--r--  1 root root  205216 May 22  2022 System.CommandLine.dll
-rwxr--r--  1 root root   51616 May 22  2022 System.CommandLine.NamingConventionBinder.dll
drwxr-xr-x  2 root root    4096 Apr  8 19:30 tr
drwxr-xr-x  2 root root    4096 Apr  8 19:30 zh-Hans
drwxr-xr-x  2 root root    4096 Apr  8 19:30 zh-Hant
```

```
root@3fda613a8159:/PlexCleaner# ./PlexCleaner --version
bash: ./PlexCleaner: No such file or directory
```

```
root@3fda613a8159:/PlexCleaner# dotnet --info
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.202/

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  7.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by richlander** [comment]
@ptr727 100% correct. I have run into this same problem. However, it isn't specific to this new pattern. This has always been a pitfall. In fact, I just ran into this same problem (just a few minutes ago) building some Go code.

**Comment by markmcgookin** [comment]
Working through this thread with a version of @richlander 's [great example](https://github.com/dotnet/dotnet-docker/issues/4388#issuecomment-1459038566) but I am noticing something strange here. This is my docker file... 

```docker
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview AS build

ARG TARGETARCH

WORKDIR /src

# restore NuGet packages
COPY ["api/*.csproj", "api/"]
COPY ["tests/*.csproj", "tests/"]

RUN dotnet restore "api/some-project-api.csproj" -a $TARGETARCH
RUN dotnet restore "tests/some-project-tests.csproj" -a $TARGETARCH

# build project
COPY ["api/.", "api/"]
COPY ["tests/.", "tests/"]

WORKDIR /src/api

RUN dotnet build "some-project-api.csproj" -c Release -a $TARGETARCH

WORKDIR /src

RUN echo "Target: $TARGETARCH"
RUN echo "Build: $BUILDPLATFORM"

# run tests on docker build
RUN if [ "$TARGETARCH" = "$BUILDPLATFORM" ] ; then dotnet test "tests/some-project-tests.csproj" -a $TARGETARCH ; fi

# publish project
FROM build AS publish

WORKDIR /src/api

RUN dotnet publish "some-project-api.csproj" -c Release -o /app/publish -a $TARGETARCH 

# run app
FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim as final

WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "some-project-api.dll"]
``` 

I was running into issues with `dotnet test` and I assumed this was sort of 'oh it has to actually execute the code so that maybe won't work cross platform' ... so I fired in a conditional if, which never seemed to fire... so I echo'd out the $BUILDPLATFORM and it never seems to be set at all... am I being stupid here? I have tried with both normal docker build and docker buildx build (which DOES build cross platform at once for me!) 

I will paste the full output below, but the relevant lines are:

```
 => CACHED [linux/arm64->amd64 build 12/14] RUN echo "Target: amd64"                                                                                    0.0s
 => CACHED [linux/arm64->amd64 build 13/14] RUN echo "Build: $BUILDPLATFORM"
```

for intel, and for arm:

```
 => CACHED [linux/arm64 build 12/14] RUN echo "Target: arm64"                                                                                           0.0s
 => CACHED [linux/arm64 build 13/14] RUN echo "Build: $BUILDPLATFORM"   
```

Thus my tests are never getting run as the if statement never fires. Am I missing something here?

```sh
docker buildx build -f dockerfile.api --push -t markmcgookin/some-project:20230421.1 -t markmcgookin/some-project:latest --platform linux/amd64,linux/arm64  . 
[+] Building 72.5s (42/42) FINISHED                                                                                                                          
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                         0.0s
 => [internal] load build definition from dockerfile.api                                                                                                0.0s
 => => transferring dockerfile: 1.09kB                                                                                                                  0.0s
 => [linux/arm64 internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim                                                          0.2s
 => [linux/amd64 internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim                                                          0.2s
 => [linux/arm64 internal] load metadata for mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview                                                           0.3s
 => [linux/arm64 build  1/14] FROM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview@sha256:d7da5c8aa2963c312ffeb43951755a4651ebdfde5f79230a37d2038cba5  0.0s
 => => resolve mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview@sha256:d7da5c8aa2963c312ffeb43951755a4651ebdfde5f79230a37d2038cba547071                 0.0s
 => [linux/arm64 final 1/3] FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim@sha256:ff588d989020412cd2d0f2781a2c1e7a144811d405eb865d2280e285d861  0.0s
 => => resolve mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim@sha256:ff588d989020412cd2d0f2781a2c1e7a144811d405eb865d2280e285d861de4d                0.0s
 => CACHED [linux/amd64 final 1/3] FROM mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim@sha256:ff588d989020412cd2d0f2781a2c1e7a144811d405eb865d2280e  0.0s
 => => resolve mcr.microsoft.com/dotnet/aspnet:7.0-bullseye-slim@sha256:ff588d989020412cd2d0f2781a2c1e7a144811d405eb865d2280e285d861de4d                0.0s
 => [internal] load build context                                                                                                                       0.4s
 => => transferring context: 29.01MB                                                                                                                    0.3s
 => CACHED [linux/arm64 build  2/14] WORKDIR /src                                                                                                       0.0s
 => CACHED [linux/arm64 build  3/14] COPY [api/*.csproj, api/]                                                                                          0.0s
 => CACHED [linux/arm64 build  4/14] COPY [tests/*.csproj, tests/]                                                                                      0.0s
 => CACHED [linux/arm64->amd64 build  5/14] RUN dotnet restore "api/some-project-api.csproj" -a amd64                                                 0.0s
 => CACHED [linux/arm64->amd64 build  6/14] RUN dotnet restore "tests/some-project-tests.csproj" -a amd64                                             0.0s
 => CACHED [linux/arm64->amd64 build  7/14] COPY [api/., api/]                                                                                          0.0s
 => CACHED [linux/arm64->amd64 build  8/14] COPY [tests/., tests/]                                                                                      0.0s
 => CACHED [linux/arm64->amd64 build  9/14] WORKDIR /src/api                                                                                            0.0s
 => CACHED [linux/arm64->amd64 build 10/14] RUN dotnet build "some-project-api.csproj" -c Release -a amd64                                            0.0s
 => CACHED [linux/arm64->amd64 build 11/14] WORKDIR /src                                                                                                0.0s
 => CACHED [linux/arm64->amd64 build 12/14] RUN echo "Target: amd64"                                                                                    0.0s
 => CACHED [linux/arm64->amd64 build 13/14] RUN echo "Build: $BUILDPLATFORM"                                                                            0.0s
 => CACHED [linux/arm64->amd64 build 14/14] RUN if [ "amd64" = "$BUILDPLATFORM" ] ; then dotnet test "tests/some-project-tests.csproj" -a amd64 ; fi  0.0s
 => CACHED [linux/arm64->amd64 publish 1/2] WORKDIR /src/api                                                                                            0.0s
 => [linux/arm64->amd64 publish 2/2] RUN dotnet publish "some-project-api.csproj" -c Release -o /app/publish -a amd64                                 1.3s
 => CACHED [linux/arm64 final 2/3] WORKDIR /app                                                                                                         0.0s
 => CACHED [linux/arm64 build  5/14] RUN dotnet restore "api/some-project-api.csproj" -a arm64                                                        0.0s
 => CACHED [linux/arm64 build  6/14] RUN dotnet restore "tests/some-project-tests.csproj" -a arm64                                                    0.0s
 => CACHED [linux/arm64 build  7/14] COPY [api/., api/]                                                                                                 0.0s
 => CACHED [linux/arm64 build  8/14] COPY [tests/., tests/]                                                                                             0.0s
 => CACHED [linux/arm64 build  9/14] WORKDIR /src/api                                                                                                   0.0s
 => CACHED [linux/arm64 build 10/14] RUN dotnet build "some-project-api.csproj" -c Release -a arm64                                                   0.0s
 => CACHED [linux/arm64 build 11/14] WORKDIR /src                                                                                                       0.0s
 => CACHED [linux/arm64 build 12/14] RUN echo "Target: arm64"                                                                                           0.0s
 => CACHED [linux/arm64 build 13/14] RUN echo "Build: $BUILDPLATFORM"                                                                                   0.0s
 => CACHED [linux/arm64 build 14/14] RUN if [ "arm64" = "$BUILDPLATFORM" ] ; then dotnet test "tests/some-project-tests.csproj" -a arm64 ; fi         0.0s
 => CACHED [linux/arm64 publish 1/2] WORKDIR /src/api                                                                                                   0.0s
 => CACHED [linux/arm64 publish 2/2] RUN dotnet publish "some-project-api.csproj" -c Release -o /app/publish -a arm64                                 0.0s
 => CACHED [linux/arm64 final 3/3] COPY --from=publish /app/publish .                                                                                   0.0s
 => [linux/amd64 final 2/3] WORKDIR /app                                                                                                                0.0s
 => [linux/amd64 final 3/3] COPY --from=publish /app/publish .                                                                                          0.0s
 => exporting to image                                                                                                                                 70.5s
 => => exporting layers                                                                                                                                 0.3s
 => => exporting manifest sha256:126ec6a256c0b985b34890e294ca564185c2c5953cf801b4059f8b5130f22e9e                                                       0.0s
 => => exporting config sha256:91f49866a4cf7bbbc4015c52e20e2906418c940304e733a2f4c2b2c9a5ac684e                                                         0.0s
 => => exporting attestation manifest sha256:9b702e17c9536fefee0baebef6b0e441657875beb9a0d301eccffe4268e63bb4                                           0.0s
 => => exporting manifest sha256:804482a55a15a84769ac0fe837b586eb4f254d635073651751f4df36bf69226e                                                       0.0s
 => => exporting config sha256:f3ad2f6c8d294082c1c2670c627653beb8fb294fb7c477a1da4540cf0085bb98                                                         0.0s
 => => exporting attestation manifest sha256:ec0a6aa61f65a3d917e7b766caee3107dcde5d71935cce6465441cd105f3afd9                                           0.0s
 => => exporting manifest list sha256:c5b30f49682e9bdf619777119256092e1e18d6cd8751d2047335dba94b3884af                                                  0.0s
 => => pushing layers                                                                                                                                   1.8s
 => => pushing manifest for docker.io/markmcgookin/some-project:20230421.1@sha256:c5b30f49682e9bdf619777119256092e1e18d6cd8751d2047335dba94b3884af       1.9s
 => => pushing manifest for docker.io/markmcgookin/some-project:latest@sha256:c5b30f49682e9bdf619777119256092e1e18d6cd8751d2047335dba94b3884af           0.9s
 
```

**Comment by goncalo-oliveira** [comment]
@markmcgookin looking at all of those `CACHED` in the output, I'm guessing you should retry with the `--no-cache` argument.

**Comment by markmcgookin** [comment]
> @markmcgookin looking at all of those `CACHED` in the output, I'm guessing you should retry with the `--no-cache` argument.

Sorry, I've run this a load and chopped and changed a lot of things, but its exactly the same. Just used `--no-cache` there. 

```
 => [linux/arm64 build 11/14] WORKDIR /src                                                                                                              0.0s
 => [linux/arm64 build 12/14] RUN echo "Target: arm64"                                                                                                  0.0s
 => [linux/arm64 build 13/14] RUN echo "Build: $BUILDPLATFORM"                                                                                          0.0s
 => [linux/arm64 build 14/14] RUN if [ "arm64" = "$BUILDPLATFORM" ] ; then dotnet test "tests/battery-logger-tests.csproj" -a arm64 ; fi                0.0s
 => [linux/arm64 publish 1/2] WORKDIR /src/api                                                                                                          0.0s
 => [linux/arm64 publish 2/2] RUN dotnet publish "battery-logger-api.csproj" -c Release -o /app/publish -a arm64                                        1.3s
 => [linux/arm64->amd64 build 11/14] WORKDIR /src                                                                                                       0.0s
 => [linux/arm64->amd64 build 12/14] RUN echo "Target: amd64"                                                                                           0.0s
 => [linux/arm64->amd64 build 13/14] RUN echo "Build: $BUILDPLATFORM"     
 ```

**Comment by campbellwray** [comment]
@markmcgookin your problem is a little different to mind, but I too noticed that `dotnet test` doesn't work properly. 

For me, I think that because there is an SDK version mismatch (i.e. I am trying to test a .NET 7 .csproj file with SDK version 8), I was getting errors telling me to change the .NET version, in my .csproj or install the .NET 7 SDK. It seems that `dotnet test` is not backwards compatible like `dotnet build` is.

For now I am just waiting for 7.0.3xx to be released, since it will have this Docker fix too.

**Comment by ptr727** [comment]
If the arg is not set, maybe explicitly declare the arg.  
For running unit tests, builder layer will always be native platform so no need to test for platform, target layer will sometimes be native platform, so must test on target/final layer.  
Need to force .NET 7 to run with .NET 8 preview.

E.g. this is what I ended up using: https://github.com/ptr727/PlexCleaner/blob/develop/Docker/Debian.dotNET.Dockerfile

E.g. builder layer:

```
ARG \
    TARGETPLATFORM \
    TARGETARCH \
    BUILDPLATFORM

ENV \
    DOTNET_ROLL_FORWARD=Major \
    DOTNET_ROLL_FORWARD_PRE_RELEASE=1
``` 

e.g. final layer

```
ARG \
    TARGETPLATFORM \
    BUILDPLATFORM
RUN if [ "$BUILDPLATFORM" = "$TARGETPLATFORM" ]; then \
        dotnet --info; \
        ffmpeg -version; \
        HandBrakeCLI --version; \
        mediainfo --version; \
        mkvmerge --version; \
        /PlexCleaner/PlexCleaner --version; \
    fi
```

**Comment by richlander** [comment]
Yes. The ARGS are not set by default. You have to set them via the pattern that @ptr727 is using. Same thing as here: https://gist.github.com/richlander/70cde3f0176d36862af80c41722acd47. The pattern in `FROM` is likely special-cased.

**Comment by richlander** [comment]
I am happy to create (or update) a sample that shows how to do unit testing as is being demonstrated here. I didn't think of that initially. Good scenario!

**Comment by markmcgookin** [comment]
Thanks @richlander that would be great. So the args are defined by default but I need to set them. Cool. I misunderstood. Thanks all for the help

**Comment by richlander** [comment]
No worries. It's simple once you know how it all works and quite mysterious before that. It took us a bit to figure out these patterns. And aspects of it are not intuitive because of the way Dockerfiles work, including various non-obvious scoping.

**Comment by douglasg14b** [comment]
This is closed, does that indicate the problem is now solved for .Net 7?

**Comment by richlander** [comment]
Great question. The problem is fixed in .NET 8 Preview 3 and 7.0.300. The latter hasn't shipped yet. I don't have a date handy on when that will be. However, you can use .NET 8 Preview 3 to build .NET 7 code as a workaround in the time.

Also, you don't need the fix if you use `-r` or `-a` in your build. If you don't then the `$BUILDPLATFORM` pattern works already w/o any fixes.

**Comment by douglasg14b** [comment]
@richlander Gotcha, and by using .Net 8 Preview 3 only for the build step, that means using that are the image in the Dockerfile instead of the .Net 7 base image correct?

We are using `--platform linux/amd64` in the `docker build` command and in the Dockerfile 🤔 

We don't use the runtime flag for `dotnet restore`, but it sounds like that by itself is a workaround?

**Comment by richlander** [comment]
> by using .Net 8 Preview 3 only for the build step, that means using that are the image in the Dockerfile instead of the .Net 7 base image correct?

Right. The SDK version you use doesn't matter for the final app/image.

> We don't use the runtime flag 

If you are not using `-r` then that's simpler.

**Comment by iliashkolyar** [comment]
Hello @richlander ,
I'm trying to use your technique to build a .NET7 application on an M1 apple machine.

**Dockerfile:**
```
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview AS build-env
ARG TARGETARCH
WORKDIR /app

COPY . ./MyApp
WORKDIR /app/MyApp/MyApp.EntryPoint

RUN dotnet restore -a $TARGETARCH

###### publish ######
FROM build-env AS publish
RUN dotnet publish --no-restore -o out -a $TARGETARCH

###### runtime image ######
FROM mcr.microsoft.com/dotnet/aspnet:7.0.5-alpine3.17
WORKDIR /app
COPY --from=publish /app/MyApp/MyApp.EntryPoint/out .
ENTRYPOINT ["dotnet", "MyApp.EntryPoint.dll"]
```

**Build command:** `docker build --platform linux/arm64 -t my-app -f ./Dockerfile .`

**Run command**: `docker run --rm -it --name my-app -p 5004:5004 my-app`

I receive the following error:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'MyApp.EntryPoint, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
qemu: uncaught target signal 6 (Aborted) - core dumped
```

If I try to check the container contents using `docker run --rm --entrypoint=sh -it my-app`, I reach the `/app` folder, in which I can see the `MyApp.EntryPoint.dll` along with all other relevant DLLs, so I'm not sure what i'm missing here.

The container does load properly when I don't use the `$TARGETARCH`/`$BUILDPLATFORM` approach (although it does crash due to qemu segmentation fault when trying to use EFCore, which I assume is related to the fact the qemu doesn't really work with .NET as you stated before).

Thanks!

**Comment by turowicz** [comment]
I get the following error for a .NET 7 project being built by the .NET 8 P4 sdk:

```
#11 [linux/amd64 build-env 4/4] RUN dotnet publish src/VU.Platform.Security.Api/VU.Platform.Security.Api.csproj -c Release --no-restore -o out/ --self-contained true -a amd64
#11 0.470 MSBuild version 17.7.0-preview-23251-02+59879b095 for .NET
#11 1.218 /usr/share/dotnet/sdk/8.0.100-preview.4.23259.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/app/src/VU.Platform.Security.Api/VU.Platform.Security.Api.csproj]
#11 1.435 /usr/share/dotnet/sdk/8.0.100-preview.4.23259.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(478,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.linux-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'linux-x64'. [/home/app/src/VU.Platform.Security.Api/VU.Platform.Security.Api.csproj]
#11 1.435 /usr/share/dotnet/sdk/8.0.100-preview.4.23259.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(478,5): error NETSDK1112: The runtime pack for Microsoft.AspNetCore.App.Runtime.linux-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'linux-x64'. [/home/app/src/VU.Platform.Security.Api/VU.Platform.Security.Api.csproj]
#11 CANCELED
```

Build.dockerfile (succeeds):
```
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview
ARG TARGETARCH
ARG BUILDPLATFORM

WORKDIR /home/app

RUN echo "Target: $TARGETARCH"
RUN echo "Build: $BUILDPLATFORM"

ADD src ./src
ADD lib ./lib

RUN dotnet restore src -a $TARGETARCH
RUN for file in $(ls src/*/*.csproj); do dotnet build $file --no-restore -c Release -a $TARGETARCH ; done
```

Publish.dockerfile (fails):
```
ARG commit
FROM --platform=$BUILDPLATFORM registry.surveily.com/platform:${commit} AS build-env
ARG project
ARG TARGETARCH
ARG BUILDPLATFORM

ENV PROJECT=${project}

RUN echo "Target: $TARGETARCH"
RUN echo "Build: $BUILDPLATFORM"

RUN dotnet publish src/${project}/${project}.csproj -c Release --no-restore --no-build -o out/ --self-contained true -a $TARGETARCH

# Build runtime image
FROM ubuntu/dotnet-deps:7.0_edge
ARG project

ENV PROJECT=${project}

WORKDIR /app

COPY --from=build-env /home/app/out .

# Prepare Entry
ADD src/entrypoint.sh entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
```

What am I doing wrong?

**Comment by goncalo-oliveira** [comment]
Wasn't this supposed to be fixed with `7.0.302` ?

I've just downloaded the SDK update and tried to build an image on my M1, but it fails with similar errors (sometimes it just freezes).

Reverting to 8.0 nightly or `preview-4` works though.

To clarify, this is just for the build process, not the runtime. And yes, I did a `--no-cache` to ensure the newer image is downloaded and running a `dotnet --version` to confirm that. I also tried using SDK `7.0.302` explicitly, same result...

**Comment by vukasinpetrovic** [comment]
@richlander Hi, I trying to solve this for days without success. I followed all of your steps but when I do that I get stuck on dotnet restore command which causes problem with package downgrade. It's just a small part of that error, it's a long list.

```> [build-env  7/11] RUN dotnet restore -a amd64:
1.523   Determining projects to restore...
8.662   Restored /src/CorporateGames.Core/CorporateGames.Core.csproj (in 6.58 sec).
41.97 /src/CorporateGames.API/CorporateGames.API.csproj : error NU1605: Warning As Error: Detected package downgrade: System.Collections from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.  [/src/CorporateGames.sln]
```

When I remove -a tags, then I guess it does not build for the proper platform. Here is my Dockerfile. Any help is appreciated.

```dockerfile
# Defines SDK image to build the apliaction
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview AS build-env
ARG TARGETARCH

# Creates folder "src" inside container and set it as current folder
WORKDIR /src

# Copies all csproj files as they are needed for restore function
COPY *.sln .
COPY CorporateGames.API/*.csproj CorporateGames.API/
COPY CorporateGames.Application/*.csproj CorporateGames.Application/
COPY CorporateGames.Core/*.csproj CorporateGames.Core/

# Restores all packages from main project (CorporateGames.API)
RUN dotnet restore -a $TARGETARCH

# Copies all files from project folder into src folder inside container
COPY . .

# Go into CorporateGames.API folder as we'll publish only that project
WORKDIR /src/CorporateGames.API

# Build the project
RUN dotnet build CorporateGames.API.csproj -c Staging --no-restore -a $TARGETARCH

# Publishes the project into publish folder inside container
RUN dotnet publish CorporateGames.API.csproj -c Staging -o /publish --no-build --no-restore -a $TARGETARCH

# Defines runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime

# Set current folder
WORKDIR /src/CorporateGames.API/publish

# Copy the publish directory from the build-env stage into the runtime image
COPY --from=build-env /publish .

ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Staging

EXPOSE 5000
ENTRYPOINT ["dotnet", "CorporateGames.API.dll"]
```

**Comment by richlander** [comment]
@vukasinpetrovic -- Package downgrades should be unrelated. If you remove all this fancy architecture targeting stuff, I assume the package downgrades still exist. Is that true?

@iliashkolyar -- This pattern enables successful building. The x64 image may or may not successfully run in QEMU, however. I just build a .NET 8 app/image with this pattern and (to my surprise) it ran as x64 on my M1 machine.

Apparently, this ENV may also help: `DOTNET_EnableWriteXorExecute=0`. Source: https://github.com/dotnet/runtime/issues/88971#issuecomment-1646793372

**Comment by vukasinpetrovic** [comment]
@richlander You are right, that problem with downgrades is not related to docker, but restoring project packages on arm that targets amd64 platform (if I specify architecture/runtime while doting dotnet restore). I'll have to research that one. If you had that problem also, any info would be much appreciated.

**Comment by richlander** [comment]
I didn't run into that problem. If you have a repro, that would be useful. The repro won't need your app, just some subset of your project file.
